import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props) {
  const { nodes, materials } = useGLTF("/merged.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[4.587, 0.375, -4.201]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={materials["Walls.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_1.geometry}
          material={materials.Darkwood3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_2.geometry}
          material={materials.Cement}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_3.geometry}
          material={materials.Darkwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_4.geometry}
          material={materials.ShinyStone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_5.geometry}
          material={materials["Tiles.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_6.geometry}
          material={materials.Iron}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_7.geometry}
          material={materials.Stone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_8.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_9.geometry}
          material={materials.LightStone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_10.geometry}
          material={materials.EMISSIVE_FIRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_11.geometry}
          material={materials.Lightwood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_12.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_13.geometry}
          material={materials["Darkwood.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_14.geometry}
          material={materials.Paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_15.geometry}
          material={materials.Crimson}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_16.geometry}
          material={materials.Log2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_17.geometry}
          material={materials.Darkmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_18.geometry}
          material={materials.Jade}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_19.geometry}
          material={materials["Crimson.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_20.geometry}
          material={materials["Log2.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_21.geometry}
          material={materials.Firewood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_22.geometry}
          material={materials.Emissive_chandelier}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_23.geometry}
          material={materials["Darkwood3.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_24.geometry}
          material={materials["Darkwood.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_25.geometry}
          material={materials["Darkwood.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_26.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_27.geometry}
          material={materials["Darkwood.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_28.geometry}
          material={materials["Metal.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/merged.glb");
